import type { Metadata } from 'next'
import {Inter, Lato, Montserrat, Poppins, Raleway} from 'next/font/google'
import './globals.css'
import {Header} from "@/app/components/header/header";

const font = Raleway({weight: '400', subsets: ['latin']})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header/>
        {children}
      <footer className={"h-[300px] flex items-center justify-center border-t bg-gray-950"}>
            <h2 className={"text-4xl text-white"}>imagine there is a nice footer here</h2>
      </footer>
      </body>
    </html>
  )
}
